'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Camera,Activity,ChevronRight,Maximize,Users} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {PLAYS,createSimulation,sampleFrame,type SimFrame} from '@/lib/simulation';
import type {StadiumViewer} from '@/lib/stadium-viewer';
const CAMS=[['broadcast','Broadcast'],['sky','Skycam'],['endzone','End zone'],['qb','Quarterback'],['follow','Ball carrier'],['stadium','Stadium orbit']];
const ROLES=['X','H','Y','Z','RB'],COLORS=['#f4c965','#66dbcb','#ed9bfb','#9bc2ff','#ff9982'];
function Choice({value,change,items,label}:{value:string;change:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={v=>v&&change(v)}><SelectTrigger aria-label={label} className="choice"><SelectValue>{items.find(i=>i[0]===value)?.[1]||value}</SelectValue></SelectTrigger><SelectContent>{items.map(([v,n])=><SelectItem value={v} key={v}>{n}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
const mount=useRef<HTMLDivElement>(null),view=useRef<StadiumViewer|null>(null),sim=useRef<ReturnType<typeof createSimulation>>(null!),clock=useRef(0),playing=useRef(false),rate=useRef(1);
if(!sim.current)sim.current=createSimulation('mesh','cover3');
const [pid,setPid]=useState('mesh'),[cover,setCover]=useState('cover3'),[cam,setCam]=useState('broadcast'),[running,setRunning]=useState(false),[speed,setSpeed]=useState('1'),[time,setTime]=useState(0),[frame,setFrame]=useState<SimFrame>(sim.current.frames[0]),[routes,setRoutes]=useState(true),[zones,setZones]=useState(false),[fans,setFans]=useState(true),[quality,setQuality]=useState('balanced'),[fps,setFps]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(''),[focus,setFocus]=useState('H'),[seed,setSeed]=useState(1924);
const play=PLAYS.find(p=>p.id===pid)!;
useEffect(()=>{if(location.port!=='5187')return;const ping=()=>fetch('/__folsom_health').catch(()=>{});ping();const timer=setInterval(ping,30000);return()=>clearInterval(timer)},[]);
const actions=useRef<any>({});
actions.current={configure:(p:string,c:string)=>{setPid(p);setCover(c);reset(p,c)},control:(cmd:string,t?:number)=>{if(cmd==='reset')reset();else if(cmd==='seek'){playing.current=false;setRunning(false);clock.current=Math.max(0,Math.min(t||0,sim.current.duration));setTime(clock.current);setFrame(sampleFrame(sim.current,clock.current))}else{playing.current=cmd==='play';setRunning(playing.current)}},camera:(c:string)=>{setCam(c);view.current?.setCamera(c)},status:()=>({ready,error,play:sim.current.play.id,coverage:sim.current.coverage,camera:cam,time:clock.current,running:playing.current,phase:sampleFrame(sim.current,clock.current).phase,fps,quality,outcome:clock.current>=sim.current.duration?sim.current.outcome:null})};
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};const settle=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
register({name:'configure_football_play',description:'Select a play and defensive coverage, resetting the visible field to pre-snap.',inputSchema:{type:'object',properties:{play:{type:'string',enum:PLAYS.map(p=>p.id)},coverage:{type:'string',enum:['cover1','cover2','cover3']},camera:{type:'string',enum:CAMS.map(c=>c[0])}},required:['play','coverage'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!PLAYS.some(p=>p.id===input.play)||!['cover1','cover2','cover3'].includes(input.coverage)||input.camera&&!CAMS.some(c=>c[0]===input.camera))throw new Error('Invalid play, coverage or camera');actions.current.configure(input.play,input.coverage);if(input.camera)actions.current.camera(input.camera);await settle();return actions.current.status()}});
register({name:'control_football_replay',description:'Play, pause, reset, or seek the selected play in the visible simulator.',inputSchema:{type:'object',properties:{command:{type:'string',enum:['play','pause','reset','seek']},time:{type:'number',minimum:0,maximum:9}},required:['command'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!['play','pause','reset','seek'].includes(input.command)||input.command==='seek'&&(!Number.isFinite(input.time)||input.time<0||input.time>9))throw new Error('Invalid replay command');actions.current.control(input.command,input.time);await settle();return actions.current.status()}});
register({name:'read_football_simulator',description:'Read loaded status, selected play, coverage, camera, replay time, measured frame rate and outcome.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>actions.current.status()});return()=>lifecycle.abort()},[]);
useEffect(()=>{let disposed=false,v:StadiumViewer|undefined;import('@/lib/stadium-viewer').then(async({StadiumViewer})=>{if(disposed||!mount.current)return;v=new StadiumViewer(mount.current);view.current=v;await v.load();if(disposed){v.dispose();return}v.setPlay(sim.current);setReady(true);let last=performance.now(),notify=0;const tick=(now:number)=>{if(disposed||!v)return;const dt=Math.min((now-last)/1000,.05);last=now;if(playing.current){clock.current=Math.min(clock.current+dt*rate.current,sim.current.duration);if(clock.current>=sim.current.duration){playing.current=false;setRunning(false)}}const f=sampleFrame(sim.current,clock.current);v.update(f,dt,playing.current);if(now-notify>100){setTime(clock.current);setFrame(f);setFps(v.fps);notify=now}requestAnimationFrame(tick)};requestAnimationFrame(tick)}).catch(e=>setError(String(e.message||e)));return()=>{disposed=true;v?.dispose()}},[]);
function reset(p=pid,c=cover,s=seed){playing.current=false;setRunning(false);clock.current=0;sim.current=createSimulation(p,c,s);setTime(0);setFrame(sim.current.frames[0]);view.current?.setPlay(sim.current);view.current?.setRoutes(routes);view.current?.setZones(zones)}
function toggle(){if(clock.current>=sim.current.duration)reset();playing.current=!playing.current;setRunning(playing.current)}
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,button,[role=combobox]'))return;if(e.code==='Space'){e.preventDefault();toggle()}if(e.code==='KeyR')reset()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
const samples=sim.current.frames.filter((f,i)=>i%10===0&&f.t<=time);
function points(metric:string,max:number){return samples.map(f=>`${f.t/9*270},${70-Math.min(max,Math.max(0,metric==='sep'?f.separations[focus]:f.gain))/max*60}`).join(' ')}
return <main className="app"><header className="topbar"><div className="brand"><div className="cu">CU</div><div><h1>FOLSOM <span>PLAY LAB</span></h1><small>BOULDER, COLORADO</small></div></div><span className="local"><i/>LOCAL SIMULATOR</span><div className="team-key"><b>COLORADO</b><i className="gold"/> OFFENSE <em/> <i className="blue"/> AWAY DEFENSE</div></header>
<div className="workspace"><aside className="playbook"><div className="eyebrow">01 / PLAYBOOK</div><h2>Call the next play.</h2><p className="muted">11 personnel · Shotgun</p><div className="plays">{PLAYS.map((p,i)=><button key={p.id} className={'play '+(p.id===pid?'selected':'')} onClick={()=>{setPid(p.id);reset(p.id)}}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{p.name}</strong><small>{p.kind.toUpperCase()} · {p.tag}</small></div><ChevronRight size={14}/></button>)}</div><label className="label">Defensive coverage</label><Choice value={cover} label="Defensive coverage" change={c=>{setCover(c);reset(pid,c)}} items={[["cover1","Cover 1 · Man free"],["cover2","Cover 2 · Two deep"],["cover3","Cover 3 · Three deep"]]}/><div className="note"><b>COACH’S NOTE</b><p>{play.note}</p></div><button className="variation" onClick={()=>{setSeed(seed+1);reset(pid,cover,seed+1)}}>New defensive reaction <RotateCcw size={14}/></button><p className="disclaimer">Rule-based play simulation. Outcomes illustrate concepts, not game predictions.</p></aside>
<section className="center"><div className="camera-bar"><Camera size={16}/><span>CAMERA</span><Choice label="Camera" value={cam} change={c=>{setCam(c);view.current?.setCamera(c)}} items={CAMS}/><button className="icon" aria-label="Fullscreen field" title="Fullscreen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.center')?.requestFullscreen()}}><Maximize size={17}/></button></div><div className="field" ref={mount}>{!ready&&<div className="loading"><strong>{error?'The 3D view could not start':'Preparing Folsom Field…'}</strong><p>{error||'Loading stadium, teams and fans'}</p></div>}<div className="field-top"><span className={'badge '+(running?'live':'')}>{running?'PLAY LIVE':time>0?'REPLAY':'PRE-SNAP'}</span><span className="caption">{play.name} <small>vs {cover.replace('cover','Cover ')}</small></span></div><div className="field-bottom"><span>Drag to look · Scroll to zoom</span><span>{fps?`${fps} FPS`:'WEBGL'} · {quality.toUpperCase()}</span></div></div>
<div className="playback"><div className="transport"><button className="snap" disabled={!ready} onClick={toggle}>{running?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}{running?'Pause':time>0&&time<sim.current.duration?'Resume':'Snap ball'}</button><button className="icon" title="Reset (R)" aria-label="Reset play" onClick={()=>reset()}><RotateCcw size={18}/></button><div className="clock"><b>{time.toFixed(1)}<small>s</small></b><span>{frame.phase}</span></div><Choice label="Playback speed" value={speed} change={s=>{setSpeed(s);rate.current=Number(s)}} items={[["0.25","¼ speed"],["0.5","½ speed"],["1","1× speed"],["1.5","1.5× speed"]]}/></div><div className="timeline"><Slider aria-label="Replay timeline" value={[time]} min={0} max={sim.current.duration} step={.025} onValueChange={v=>{playing.current=false;setRunning(false);clock.current=Array.isArray(v)?v[0]:v;setTime(clock.current);setFrame(sampleFrame(sim.current,clock.current))}}/><div><span>SNAP</span><span>READ</span><span>EXECUTE</span><span>WHISTLE</span></div></div></div><div className="options"><label><Switch checked={routes} onCheckedChange={v=>{setRoutes(v);view.current?.setRoutes(v)}}/>Route colors</label><label><Switch checked={zones} onCheckedChange={v=>{setZones(v);view.current?.setZones(v)}}/>Coverage zones</label><label><Switch checked={fans} onCheckedChange={v=>{setFans(v);view.current?.setCrowd(v)}}/>Fans</label><Choice value={quality} label="Graphics quality" change={q=>{setQuality(q);view.current?.setQuality(q)}} items={[["low","Battery saver"],["balanced","Balanced"],["high","High detail"]]}/></div></section>
<aside className="analysis"><div className="eyebrow">02 / LIVE ANALYSIS <Activity size={15}/></div><div className="gain"><span>YARDS FROM SCRIMMAGE</span><strong>{frame.gain>=0?'+':''}{frame.gain.toFixed(1)}<small>YD</small></strong><p>{time>=sim.current.duration?sim.current.outcome:frame.phase}</p></div><div className="metric"><b>Receiver separation</b><span>YARDS</span></div><div className="receivers">{ROLES.map((id,i)=><button className={focus===id?'focused':''} key={id} onClick={()=>{setFocus(id);view.current?.setFocus(id)}}><i style={{background:COLORS[i]}}/><strong>{id}</strong><span className="bar"><i style={{width:`${Math.min(100,frame.separations[id]/8*100)}%`,background:COLORS[i]}}/></span><b>{frame.separations[id].toFixed(1)}</b></button>)}</div>{[['sep',`${focus} · Separation`,8],['gain','Ball progress',40]].map(([key,title,max])=><div className="chart" key={key}><div><b>{title}</b><span>0–{max} yd</span></div><svg viewBox="0 0 280 84" role="img" aria-label={String(title)+' chart'}><path d="M0 10H280 M0 40H280 M0 70H280" className="gridline"/><polyline points={points(String(key),Number(max))} fill="none" stroke={key==='sep'?COLORS[ROLES.indexOf(focus)]:'#d2ad62'} strokeWidth="2.5"/></svg><footer><span>0s</span><span>9s</span></footer></div>)}<div className="readout"><span>QB READ</span><strong>{frame.target?`${frame.target} · ${frame.phase==='Pass airborne'?'Ball in flight':'Selected receiver'}`:'Scanning coverage'}</strong></div><div className="crowd-note"><Users size={18}/><p>Colorado black & gold crowd.<br/><small>Instanced fans · adaptive resolution</small></p></div></aside></div><footer className="footer"><span>FOLSOM FIELD <b>BOULDER · 5,360 FT</b></span><span>COLORADO BLACK & GOLD</span><span>SPACE Play / pause · R Reset</span></footer></main>
}
